name: My First Action
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Getting my project
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.19.0'
    - name: Check Node version
      run: node --version